version: '3'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    networks:
      - my-network
    volumes:
      - .:/usr/src/app
    command: node puppeteerApi.js

networks:
  my-network:
    driver: bridge